sonar.projectKey=Guichardx2_devops-satc
sonar.organization=guichardx2
sonar.host.url=https://sonarcloud.io

sonar.sources=src
sonar.exclusions=**/node_modules/**,**/dist/**,**/*.test.ts,**/*.test.tsx,**/*.spec.ts,**/*.spec.tsx
